const ActionTypes = {
    USERNAME:'USERNAME',
    CURRENTUSER:'CURRENTUSER',
    ALLUSERS:'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    USERINFO : 'USERINFO'
}

export default ActionTypes;